// Style reminder: replicate legacy history.html with a simple Game History heading, compact glass result cards, and trophy empty state.

import { Loader2, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { usePlayer } from "@/contexts/PlayerContext";
import { playerApi, type Round } from "@/lib/gateway";
import { etb, relativeDate } from "@/lib/format";

export default function History() {
  const { player } = usePlayer();
  const playerId = String(player?.user_id || player?.id || "");
  const [rounds, setRounds] = useState<Round[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); playerApi.history().then((data) => { if (!active) return; const source = Array.isArray(data) ? data : data.rounds || []; const personal = source.filter((round) => round.status === "completed" && (round.players ? Object.prototype.hasOwnProperty.call(round.players, playerId) : true)).sort((left, right) => new Date(String(right.completed_at || right.created_at || 0)).getTime() - new Date(String(left.completed_at || left.created_at || 0)).getTime()).slice(0, 3); setRounds(personal); }).catch((e) => active && setError(e instanceof Error ? e.message : "Unable to load history")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [playerId]);
  return <div className="min-h-[calc(100vh-56px)] bg-[linear-gradient(180deg,#0D1117_0%,#0A1628_40%,#111827_100%)] px-4 py-4"><h2 className="mb-1 text-xl font-bold text-white">My Recent Games</h2><p className="mb-4 text-xs text-white/40">Your three most recent completed rounds.</p><div className="space-y-3">{loading ? <><div className="loading-shimmer h-20 rounded-xl border border-white/10 bg-[#1A1A2E]/70" /><div className="loading-shimmer h-20 rounded-xl border border-white/10 bg-[#1A1A2E]/70" /><div className="loading-shimmer h-20 rounded-xl border border-white/10 bg-[#1A1A2E]/70" /></> : error ? <div className="glass rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-center text-sm text-red-300">{error}</div> : rounds.length === 0 ? <div className="py-12 text-center"><div className="mb-4 text-5xl">🏆</div><p className="text-white/50">No completed games yet</p><p className="mt-1 text-sm text-white/30">Your completed rounds will appear here.</p></div> : rounds.map((round, index) => { const won = (round.winners || []).some((winner) => String(winner) === playerId); return <article key={round.id || round.round_id || index} className="glass rounded-xl border border-white/10 bg-[#1A1A2E]/75 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-white">Round #{String(round.id || round.round_id || "—").slice(0, 8)}</p><p className="mt-1 text-[11px] text-white/40">{relativeDate(round.completed_at || round.created_at)} · {round.player_count || 0} cartelas</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${won ? "bg-emerald-500/10 text-emerald-400" : "bg-white/10 text-white/50"}`}>{won ? "Winner" : "Completed"}</span></div><div className="mt-3 flex items-center justify-between border-t border-white/10 pt-2.5 text-[11px]"><span className="text-white/40">Derash pool</span><span className="font-black text-[#8B5CF6]">{etb(round.derash)}</span></div>{round.prize_per_winner ? <div className="mt-1 flex items-center justify-between text-[11px]"><span className="flex items-center gap-1 text-white/40"><Trophy className="h-3 w-3" /> Prize per winner</span><span className="font-black text-[#FFB45C]">{etb(round.prize_per_winner)}</span></div> : null}</article>; })}</div></div>;
}
