// Style reminder: history keeps the original compact glass cards and clear status colors while loading server history safely.

import { Clock3, Loader2, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { playerApi, type Round } from "@/lib/gateway";
import { etb, relativeDate } from "@/lib/format";

export default function History() {
  const [rounds, setRounds] = useState<Round[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; playerApi.history().then((data) => active && setRounds(Array.isArray(data) ? data : [])).catch((e) => active && setError(e instanceof Error ? e.message : "Unable to load history")).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  return <div className="px-3 py-4"><div className="mb-4 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/30">Your activity</p><h1 className="mt-1 text-2xl font-black">History</h1></div><Clock3 className="h-5 w-5 text-[#FF8C00]" /></div>{loading ? <Loading /> : error ? <State title="History unavailable" body={error} /> : rounds.length === 0 ? <State title="No completed rounds yet" body="Your completed games will appear here." /> : <div className="space-y-2.5">{rounds.slice(0, 50).map((round, index) => <article key={round.id || round.round_id || index} className="rounded-2xl border border-white/[0.06] bg-[#1A1A2E]/80 px-4 py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black">Round #{String(round.id || round.round_id || "—").slice(0, 8)}</p><p className="mt-1 text-[11px] text-white/35">{relativeDate(round.completed_at || round.created_at)} · {round.player_count || 0} cartelas</p></div><span className="rounded-full bg-[#10B981]/10 px-2.5 py-1 text-[10px] font-bold text-[#34D399]">Completed</span></div><div className="mt-3 flex items-center justify-between border-t border-white/[0.06] pt-2.5 text-[11px]"><span className="text-white/35">Derash pool</span><span className="font-black text-[#C084FC]">{etb(round.derash)}</span></div>{round.prize_per_winner ? <div className="mt-1 flex items-center justify-between text-[11px]"><span className="flex items-center gap-1 text-white/35"><Trophy className="h-3 w-3" /> Prize per winner</span><span className="font-black text-[#FFB45C]">{etb(round.prize_per_winner)}</span></div> : null}</article>)}</div>}</div>;
}
function Loading() { return <div className="flex items-center justify-center rounded-2xl border border-white/[0.06] bg-[#1A1A2E]/70 py-12 text-white/40"><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Loading history</div>; }
function State({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-white/[0.06] bg-[#1A1A2E]/70 px-5 py-12 text-center"><p className="text-sm font-black">{title}</p><p className="mt-2 text-xs text-white/40">{body}</p></div>; }
