// Style reminder: replicate legacy profile.html with centered avatar/identity, three compact metrics, estimated earnings, settings/help rows, and Log Out.

import { ChevronRight, HelpCircle, LogOut, Settings } from "lucide-react";
import { usePlayer } from "@/contexts/PlayerContext";
import { walletValue } from "@/lib/format";

function telegramPopup(title: string, message: string) { (window as Window & { Telegram?: { WebApp?: { showPopup?: (options: { title: string; message: string }) => void } } }).Telegram?.WebApp?.showPopup?.({ title, message }); }

export default function Profile() {
  const { player, logout } = usePlayer();
  const wins = player?.wins || 0;
  const games = player?.total_games || player?.games_played || 0;
  const winRate = games ? `${Math.round((wins / games) * 100)}%` : "0%";
  return <div className="min-h-[calc(100vh-56px)] bg-[linear-gradient(180deg,#0D1117_0%,#0A1628_40%,#111827_100%)] px-4 py-4"><h2 className="mb-6 text-xl font-bold text-white">Profile</h2><div className="mb-6 text-center"><div className="mx-auto mb-3 flex h-20 w-20 items-center justify-center rounded-full bg-gradient-to-br from-[#FF8C00] to-[#FF6B00] text-3xl font-black text-white">{(player?.first_name || "?").charAt(0).toUpperCase()}</div><div className="text-xl font-bold text-white">{player?.first_name || "Loading…"}</div><div className="text-sm text-white/50">{player?.username ? `@${player.username}` : "@username"}</div></div><div className="mb-6 grid grid-cols-3 gap-3"><Metric value={games} label="Games" tone="text-[#3B82F6]" /><Metric value={wins} label="Wins" tone="text-[#10B981]" /><Metric value={winRate} label="Win Rate" tone="text-[#FF8C00]" /></div><div className="glass mb-6 rounded-2xl border border-white/10 bg-[#1A1A2E]/75 p-4 text-center"><div className="mb-1 text-xs uppercase text-white/50">Estimated Earnings</div><div className="text-3xl font-black text-[#10B981]">—</div><p className="mt-1 text-[10px] text-white/30">Settled earnings are reflected in your wallet balance.</p></div><div className="mb-6 space-y-3"><button onClick={() => telegramPopup("Settings", "Account settings coming soon!")} className="glass flex w-full items-center gap-3 rounded-xl border border-white/10 bg-[#1A1A2E]/70 p-4 text-left transition-colors hover:bg-white/10"><Settings className="h-5 w-5 text-white/70" /><span className="text-sm text-white/70">Account Settings</span><ChevronRight className="ml-auto h-4 w-4 text-white/30" /></button><button onClick={() => telegramPopup("Help", "Need help? Contact @kelembingo_bot")} className="glass flex w-full items-center gap-3 rounded-xl border border-white/10 bg-[#1A1A2E]/70 p-4 text-left transition-colors hover:bg-white/10"><HelpCircle className="h-5 w-5 text-white/70" /><span className="text-sm text-white/70">Help &amp; Support</span><ChevronRight className="ml-auto h-4 w-4 text-white/30" /></button></div><button onClick={logout} className="w-full rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-center transition-transform active:scale-[0.97]"><span className="flex items-center justify-center gap-2 text-sm font-semibold text-red-400"><LogOut className="h-4 w-4" /> Log Out</span></button></div>;
}
function Metric({ value, label, tone }: { value: React.ReactNode; label: string; tone: string }) { return <div className="glass rounded-xl border border-white/10 bg-[#1A1A2E]/70 p-3 text-center"><div className={`text-xl font-bold ${tone}`}>{value}</div><div className="mt-1 text-[10px] text-white/50">{label}</div></div>; }
